const SONGS = [
  {
    id:             'audio1',
    title:          'Hyper Kawaii idol',
    type:           'free',
    description:    '「Hyper Kawaii idol」は、自然で流れるようなメロディーが特徴で、穏やかな中に力強さを感じさせる楽曲です。壮大でドラマチックな雰囲気が魅力で、リラックスしながらもエピックな気分を楽しみたい時におすすめです。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/Hyper Kawaii idol.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Hyper Kawaii idol.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '可愛い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio2',
    title:          'サマーブリーズ・チル',
    type:           'free',
    description:    '「サマーブリーズ・チル」は、エネルギッシュでダイナミックなサウンドが心地よく響く、バランスの取れた楽曲です。リラックスしたい時や、自然の風景を思い浮かべながらの作業時にぴったりです。暖かくスムーズな音色が、心を落ち着かせてくれます。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/サマーブリーズ・チル.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/サマーブリーズ・チル.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio3',
    title:          'バグかわヒロイン',
    type:           'free',
    description:    '「バグかわヒロイン」は、エネルギッシュでダイナミックなビートが特徴の楽曲です。元気を出したい時や集中したいタイミングにぴったりで、聴くたびにパワフルな気分になれます。壮大なドラマを感じさせるサウンドは、自然な風景を彩るBGMとしても最適です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/バグかわヒロイン.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/バグかわヒロイン.mp3',
    licenses:       [],
    tags:           ['明るい', '穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio4',
    title:          '冬の余韻 - Gentle Snow Ambient',
    type:           'free',
    description:    '「冬の余韻 - Gentle Snow Ambient」は、静かに流れる時間と共に心を深く落ち着かせてくれるアンビエント曲です。暗くミステリアスな響きが、幻想的な冬の風景を思い起こさせます。リラックスしたい時や、静かな環境を求めるシーンにぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/冬の余韻 - Gentle Snow Ambient.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/冬の余韻 - Gentle Snow Ambient.mp3',
    licenses:       [],
    tags:           ['不思議', '暗い', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio5',
    title:          'くつろぎトーク空間',
    type:           'free',
    description:    '「くつろぎトーク空間」は、心地よいリズムと静かなパワーが織りなすミステリアスな一曲です。リラックスしたい夜や集中したい時、またはダークファンタジーの世界に没頭したい瞬間にぴったりです。深く流れるような音楽が、あなたを幻想的な空間へと導いてくれます。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/くつろぎトーク空間.mp3',
    licenses:       [],
    tags:           ['力強い', '不思議', '暗い', '壮大', 'ゲーム', 'シネマ', 'ヒーリング'],
  },

  // ↓ 新しい曲はここに追加 ↓
];
