const SONGS = [
  {
    id:             'audio1',
    title:          'Hyper Kawaii idol',
    type:           'free',
    description:    '「Hyper Kawaii idol」は、自然で流れるようなメロディーが特徴で、穏やかな中に力強さを感じさせる楽曲です。壮大でドラマチックな雰囲気が魅力で、リラックスしながらもエピックな気分を楽しみたい時におすすめです。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/Hyper Kawaii idol.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Hyper Kawaii idol.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '可愛い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio2',
    title:          'サマーブリーズ・チル',
    type:           'free',
    description:    '「サマーブリーズ・チル」は、エネルギッシュでダイナミックなサウンドが心地よく響く、バランスの取れた楽曲です。リラックスしたい時や、自然の風景を思い浮かべながらの作業時にぴったりです。暖かくスムーズな音色が、心を落ち着かせてくれます。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/サマーブリーズ・チル.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/サマーブリーズ・チル.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio3',
    title:          'バグかわヒロイン',
    type:           'free',
    description:    '「バグかわヒロイン」は、エネルギッシュでダイナミックなビートが特徴の楽曲です。元気を出したい時や集中したいタイミングにぴったりで、聴くたびにパワフルな気分になれます。壮大なドラマを感じさせるサウンドは、自然な風景を彩るBGMとしても最適です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/バグかわヒロイン.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/バグかわヒロイン.mp3',
    licenses:       [],
    tags:           ['明るい', '穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio4',
    title:          '冬の余韻 - Gentle Snow Ambient',
    type:           'free',
    description:    '「冬の余韻 - Gentle Snow Ambient」は、静かに流れる時間と共に心を深く落ち着かせてくれるアンビエント曲です。暗くミステリアスな響きが、幻想的な冬の風景を思い起こさせます。リラックスしたい時や、静かな環境を求めるシーンにぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/冬の余韻 - Gentle Snow Ambient.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/冬の余韻 - Gentle Snow Ambient.mp3',
    licenses:       [],
    tags:           ['不思議', '暗い', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio5',
    title:          'くつろぎトーク空間',
    type:           'free',
    description:    '「くつろぎトーク空間」は、心地よいリズムと静かなパワーが織りなすミステリアスな一曲です。リラックスしたい夜や集中したい時、またはダークファンタジーの世界に没頭したい瞬間にぴったりです。深く流れるような音楽が、あなたを幻想的な空間へと導いてくれます。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/くつろぎトーク空間.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/くつろぎトーク空間.mp3',
    licenses:       [],
    tags:           ['穏やか', 'お洒落', '切ない', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio6',
    title:          'Calm Street Echo – 静かな街のエコー',
    type:           'free',
    description:    '「Calm Street Echo – 静かな街のエコー」は、静寂な街に潜むエネルギーとミステリアスな雰囲気を捉えた一曲です。物語が展開するようなドラマチックなサウンドが、深い夜や想像力を刺激する瞬間にぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          '',
    licenses:       [],
    tags:           ['力強い', '不思議', '暗い', '速い', '壮大', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio7',
    title:          'Entry Point Live',
    type:           'free',
    description:    '「Entry Point Live」は、エネルギッシュでダイナミックな音楽体験を提供します。パワフルで力強いこのトラックは、ドラマティックで壮大なシーンや美しい風景にぴったりです。集中力を高めたい時や、モチベーションを上げたいシーンにぜひお使いください。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Entry Point Live.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio8',
    title:          'Gale Battle Dance – 疾風戦舞録',
    type:           'free',
    description:    '「疾風戦舞録」は、力強くダイナミックなエネルギーに満ちた楽曲です。エピックでドラマチックなムードが、特に冒険心をかき立てたい場面や、壮大な風景を背景にした映像作品に最適です。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          '',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'クラシック', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio9',
    title:          'Press Start Now',
    type:           'free',
    description:    '「Press Start Now」は、エネルギッシュでダイナミックなサウンドが特徴の楽曲です。ドラマチックで壮大な雰囲気を持ち、何か新しいことを始める時や挑戦する際にぴったりです。風景をイメージさせるような静かさも兼ね備えており、自然を感じる瞬間に使ってみてください。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Press Start Now.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio10',
    title:          'Radiant Strike Flow – ラディアントストライクフロー',
    type:           'free',
    description:    '「Radiant Strike Flow」は活力溢れるエネルギッシュなサウンドが特徴の楽曲です。滑らかで自然なムードが融合し、シネマティックで風景を思わせる雰囲気が漂います。作業や創造的な時間にピッタリの一曲です。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          '',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio11',
    title:          'Scarlet Thunder Beat – 緋雷ビート',
    type:           'free',
    description:    '「Scarlet Thunder Beat – 緋雷ビート」は、力強くエネルギッシュなビートが特徴で、心を奮い立たせる一曲です。ドラマチックなシーンや、力強い展開を演出したい時にぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          '',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio12',
    title:          'Session Begin!',
    type:           'free',
    description:    '"Session Begin!"は力強くダイナミックなエネルギーに満ちた楽曲で、ドラマチックで壮大な雰囲気が漂います。活気に溢れる音楽は、仕事や運動、創造的なセッションの始まりにぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          '',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio13',
    title:          'Shadow Pulse Siege – 影のパルスシージ',
    type:           'free',
    description:    '"Shadow Pulse Siege – 影のパルスシージ"は、エネルギッシュで力強いムードを持つ楽曲です。劇的で壮大な雰囲気があり、何か大きな挑戦に向かう時や集中したい時にぴったりです。自然の広大さを感じさせる音楽が、心を燃え立たせます。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          '',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'クラシック', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio14',
    title:          'Skyblade Fantasy – 蒼空ブレードファンタジー',
    type:           'free',
    description:    '"Skyblade Fantasy – 蒼空ブレードファンタジー"は、壮大さと繊細さが融合した音楽で、広大な風景を思い描きながらリラックスしたい時に最適です。劇的で力強い旋律が、自然の中での冒険や深い感動を感じさせます。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          '',
    licenses:       [],
    tags:           ['穏やか', '力強い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio15',
    title:          'Start Dash Live',
    type:           'free',
    description:    '「Start Dash Live」は、エネルギッシュでダイナミックなサウンドを持ち、気分を盛り上げたいときや何かをスタートする場面にぴったりの曲です。力強く、アップビートなメロディが、聴く人の心を集中させ、元気づけてくれます。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Start Dash Live.mp3',
    licenses:       [],
    tags:           ['明るい', '穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio16',
    title:          'Start Up Channel',
    type:           'free',
    description:    '「Start Up Channel」は、あなたのプロジェクトにエネルギーと活気をもたらす一曲です。このダイナミックでパワフルなサウンドは、特にドラマティックなシーンや壮大なプレゼンテーションに最適です。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Start Up Channel.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'EDM', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio17',
    title:          'しろいひととき',
    type:           'free',
    description:    '「しろいひととき」は、力強くも温かみのあるサウンドが特徴の楽曲です。エネルギッシュでダイナミックなムードは、ドラマティックな場面や壮大な風景を思い起こさせます。集中したい時やモチベーションを高めたい時におすすめです。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/しろいひととき.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio18',
    title:          'ひだまり和音',
    type:           'free',
    description:    '「ひだまり和音」は、心を温かく包み込むようなエネルギッシュでダイナミックな曲です。忙しい日常の中でのひとときのリフレッシュや、クリエイティブな作業をする際のBGMにぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ひだまり和音.mp3',
    licenses:       [],
    tags:           ['穏やか', '爽やか', '力強い', '日常', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio19',
    title:          'ふわっとスマイル',
    type:           'free',
    description:    '「ふわっとスマイル」は、力強くエネルギッシュなムードと、穏やかで自然な雰囲気を兼ね備えた一曲です。忙しい日々の合間に、気分をリフレッシュしたい時や、ダイナミックな景観を楽しみたい時にぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ふわっとスマイル.mp3',
    licenses:       [],
    tags:           ['穏やか', '爽やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio20',
    title:          'ふわふわ重力オフ',
    type:           'free',
    description:    '「ふわふわ重力オフ」は、エネルギッシュでパワフルなメロディが特徴のトラックです。ドラマチックで大胆な雰囲気が漂い、景色を一変させるような壮大なサウンドスケープです。集中したい時や活力を取り戻したい時にぜひお楽しみください。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ふわふわ重力オフ.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'EDM', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio21',
    title:          'ぽかぽかメロディタイム',
    type:           'free',
    description:    '「ぽかぽかメロディタイム」は、エネルギッシュで力強いメロディが心を躍らせる一曲です。ダイナミックな展開が続くため、作業中やリフレッシュしたい時にぴったり。自然で温かみのあるサウンドが、あなたの日常にエピックなひとときを演出します。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ぽかぽかメロディタイム.mp3',
    licenses:       [],
    tags:           ['穏やか', '爽やか', '力強い', '日常', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio22',
    title:          'ましゅまろステップ',
    type:           'free',
    description:    '「ましゅまろステップ」は、活力に満ちた力強いエネルギーを秘めた楽曲です。ドラマチックな雰囲気と壮大なサウンドが特徴で、心が躍る瞬間やインスピレーションが欲しい時にぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ましゅまろステップ.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'クラシック', 'EDM', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio23',
    title:          'ゆめうつつ通信中',
    type:           'free',
    description:    '「ゆめうつつ通信中」は、エネルギッシュで力強いサウンドが特徴の楽曲です。ドラマチックで壮大な雰囲気が、聴く人を特別な世界へと誘います。集中したい時や気分を高めたい瞬間にぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ゆめうつつ通信中.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio24',
    title:          'ゆるふわノイズ',
    type:           'free',
    description:    '「ゆるふわノイズ」は、エネルギッシュでダイナミックな雰囲気を持つ楽曲です。風景を描くような壮大な感覚があり、日常の中でエピックな瞬間を感じたい時に特におすすめです。温かくも力強い音楽が、シーンにインパクトを与えます。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ゆるふわノイズ.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '日常', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio25',
    title:          'クロノヒルズ',
    type:           'free',
    description:    '「クロノヒルズ」はドラマチックで壮大なムードを醸し出しながらも、聴く人に力強さと暖かさを感じさせる楽曲です。まるで広大な風景を目の当たりにするようなこの曲は、特に集中したい作業中やエネルギッシュに活動したい時にぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/クロノヒルズ.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'クラシック', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio26',
    title:          'グラビティプレイン',
    type:           'free',
    description:    '「グラビティプレイン」は、一瞬で気分を高めてくれるエネルギッシュな楽曲です。風景を描き出すようなダイナミックな音楽は、集中したい時やインスピレーションを求めるシーンにぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/グラビティプレイン.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'EDM', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio27',
    title:          '微睡小道',
    type:           'free',
    description:    '「微睡小道」は、ドラマチックでエピックな雰囲気を持つBGMです。力強くダイナミックなサウンドが、ダークファンタジーやミステリアスなシーンによく合います。深みのある音楽が、ストーリーや映像に奥行きを加えてくれるでしょう。',
    price:          0,
    duration:       '--:--',
    jacket:         '',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/微睡小道.mp3',
    licenses:       [],
    tags:           ['力強い', '不思議', '暗い', '速い', '壮大', 'ゲーム', 'シネマ', 'ヒーリング'],
  },

  // ↓ 新しい曲はここに追加 ↓
];
