const SONGS = [
  {
    id:             'audio1',
    title:          'Hyper Kawaii idol',
    type:           'free',
    description:    '「Hyper Kawaii idol」は、自然で流れるようなメロディーが特徴で、穏やかな中に力強さを感じさせる楽曲です。壮大でドラマチックな雰囲気が魅力で、リラックスしながらもエピックな気分を楽しみたい時におすすめです。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/Hyper Kawaii idol.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Hyper Kawaii idol.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '可愛い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio2',
    title:          'サマーブリーズ・チル',
    type:           'free',
    description:    '「サマーブリーズ・チル」は、エネルギッシュでダイナミックなサウンドが心地よく響く、バランスの取れた楽曲です。リラックスしたい時や、自然の風景を思い浮かべながらの作業時にぴったりです。暖かくスムーズな音色が、心を落ち着かせてくれます。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/サマーブリーズ・チル.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/サマーブリーズ・チル.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio3',
    title:          'バグかわヒロイン',
    type:           'free',
    description:    '「バグかわヒロイン」は、エネルギッシュでダイナミックなビートが特徴の楽曲です。元気を出したい時や集中したいタイミングにぴったりで、聴くたびにパワフルな気分になれます。壮大なドラマを感じさせるサウンドは、自然な風景を彩るBGMとしても最適です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/バグかわヒロイン.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/バグかわヒロイン.mp3',
    licenses:       [],
    tags:           ['明るい', '穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio4',
    title:          '冬の余韻 - Gentle Snow Ambient',
    type:           'free',
    description:    '「冬の余韻 - Gentle Snow Ambient」は、静かに流れる時間と共に心を深く落ち着かせてくれるアンビエント曲です。暗くミステリアスな響きが、幻想的な冬の風景を思い起こさせます。リラックスしたい時や、静かな環境を求めるシーンにぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/冬の余韻 - Gentle Snow Ambient.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/冬の余韻 - Gentle Snow Ambient.mp3',
    licenses:       [],
    tags:           ['不思議', '暗い', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio5',
    title:          'くつろぎトーク空間',
    type:           'free',
    description:    '「くつろぎトーク空間」は、心地よいリズムと静かなパワーが織りなすミステリアスな一曲です。リラックスしたい夜や集中したい時、またはダークファンタジーの世界に没頭したい瞬間にぴったりです。深く流れるような音楽が、あなたを幻想的な空間へと導いてくれます。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/くつろぎトーク空間.png',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/くつろぎトーク空間.mp3',
    licenses:       [],
    tags:           ['穏やか', 'お洒落', '切ない', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio7',
    title:          'Entry Point Live',
    type:           'free',
    description:    '「Entry Point Live」は、力強くエネルギッシュなムードを持つ曲で、緊迫した瞬間や大自然の広がる風景をイメージしながら聴くのにぴったりです。特にドラマチックなシーンや、描き出すような風景に迫力を加えたいときに最適です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/Entry Point Live.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Entry Point Live.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio9',
    title:          'Press Start Now',
    type:           'free',
    description:    '「Press Start Now」は、エネルギッシュでダイナミックなムードを持ちながら、壮大でドラマチックな雰囲気を演出します。新たなスタートや挑戦の瞬間、モチベーションを高めたいときにおすすめの一曲です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/Press Start Now.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Press Start Now.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio15',
    title:          'Start Dash Live',
    type:           'free',
    description:    '「Start Dash Live」は、まるで大冒険の幕開けを告げる力強い一曲。元気を引き出したい朝や、大切なプロジェクトに取り組む前のウォームアップに最適です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/Start Dash Live.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Start Dash Live.mp3',
    licenses:       [],
    tags:           ['明るい', '穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio16',
    title:          'Start Up Channel',
    type:           'free',
    description:    '「Start Up Channel」は、エネルギッシュで力強いムードを持つ曲で、新しいプロジェクトを始めるときや、やる気を引き出したい瞬間にぴったりです。ドラマティックかつ壮大なサウンドが、聴く人の心を奮い立たせることでしょう。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/Start Up Channel.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/Start Up Channel.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio17',
    title:          'しろいひととき',
    type:           'free',
    description:    '「しろいひととき」は、エネルギッシュでダイナミックなムードを持つ曲です。壮大でドラマティックな雰囲気の中に、暖かさと自然な美しさを感じられます。仕事や勉強の合間にリラックスしたい時や、インスピレーションを得たい時にぴったりの一曲です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/しろいひととき.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/しろいひととき.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio18',
    title:          'ひだまり和音',
    type:           'free',
    description:    '「ひだまり和音」は、エネルギッシュでダイナミックなサウンドが特徴の楽曲です。壮大でドラマチックな雰囲気を持ち合わせており、自然の風景をバックにした動画や、感動的なシーンの演出にぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/ひだまり和音.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ひだまり和音.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'クラシック', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio19',
    title:          'ふわっとスマイル',
    type:           'free',
    description:    '「ふわっとスマイル」は、元気で力強いリズムが特徴の楽曲です。自然の風景を思い描きながら、気持ちをリフレッシュしたいときにぴったりです。ドラマティックで心温まる瞬間に彩りを加えること間違いなしの一曲です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/ふわっとスマイル.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ふわっとスマイル.mp3',
    licenses:       [],
    tags:           ['明るい', '楽しい', '穏やか', '爽やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio20',
    title:          'ふわふわ重力オフ',
    type:           'free',
    description:    '「ふわふわ重力オフ」は、日常の喧騒を忘れて自然の風景に浸るような、壮大で力強いエネルギーを感じられる楽曲です。朝のスタートダッシュにもぴったりで、何か新しいことを始める際のモチベーションアップに最適です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/ふわふわ重力オフ.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ふわふわ重力オフ.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '日常', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio21',
    title:          'ぽかぽかメロディタイム',
    type:           'free',
    description:    '「ぽかぽかメロディタイム」は、エネルギッシュでダイナミックなメロディが魅力の楽曲です。風景の中を駆け巡るような壮大な雰囲気を持ち、パワフルで暖かいサウンドが日常に活力を与えます。特にリラックスしたい時や、自然と調和した時間を楽しみたい時に最適です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/ぽかぽかメロディタイム.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ぽかぽかメロディタイム.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '日常', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio22',
    title:          'ましゅまろステップ',
    type:           'free',
    description:    '「ましゅまろステップ」は、エネルギッシュでダイナミックなサウンドが特徴の楽曲です。力強く、かつ温かみを感じるこの音楽は、創造的なアイデアを膨らませたい時や気分を高めたい時にぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/ましゅまろステップ.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ましゅまろステップ.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'EDM', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio23',
    title:          'ゆめうつつ通信中',
    type:           'free',
    description:    '「ゆめうつつ通信中」は、その名の通り、夢見心地な世界へと誘うダイナミックで力強い楽曲です。エピックで力強い雰囲気は、新たなチャレンジや冒険の場面によく合います。自然の風景を眺めながら、心を解放するひとときにも最適です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/ゆめうつつ通信中.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ゆめうつつ通信中.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio24',
    title:          'ゆるふわノイズ',
    type:           'free',
    description:    '「ゆるふわノイズ」は、エネルギッシュでダイナミックな雰囲気を持ち、前向きで情熱的な印象を与えます。この曲は、ドラマティックな瞬間や雄大な景色を思わせるシーンにぴったりで、静けさと力強さが融合した独特の音色です。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/ゆるふわノイズ.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/ゆるふわノイズ.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio25',
    title:          'クロノヒルズ',
    type:           'free',
    description:    '「クロノヒルズ」は、ドラマティックでエピックな雰囲気を持つ楽曲です。エネルギッシュでダイナミックなリズムは、風景を描き出すような壮大なシーンにぴったりです。特に集中力が必要な作業やモチベーションを高めたいときにおすすめです。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/クロノヒルズ.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/クロノヒルズ.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio26',
    title:          'グラビティプレイン',
    type:           'free',
    description:    '「グラビティプレイン」は、エネルギッシュでダイナミックなビートが特徴の一曲です。ダイナミックかつパワフルなサウンドが、壮大でドラマチックなシーンを彩ります。激しい運動をする時や気分を高めたい時にぴったりです。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/グラビティプレイン.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/グラビティプレイン.mp3',
    licenses:       [],
    tags:           ['穏やか', '力強い', '激しい', '速い', '壮大', 'アンビエント', 'ゲーム', 'シネマ', 'ヒーリング'],
  },
  {
    id:             'audio27',
    title:          '微睡小道',
    type:           'free',
    description:    '「微睡小道」は、エネルギッシュでダイナミックなムードを持ちながらも、暗く神秘的な要素が混じったドラマチックな曲です。強力で濃厚なサウンドは、エピックな瞬間や壮大なシーンにぴったりです。特にダークファンタジーやノワールな映像作品のバックグラウンドミュージックとして重宝します。',
    price:          0,
    duration:       '--:--',
    jacket:         'images/微睡小道.jpg',
    jacketGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    jacketEmoji:    '🎵',
    audio:          'audio/微睡小道.mp3',
    licenses:       [],
    tags:           ['力強い', '不思議', '暗い', '速い', '壮大', 'ゲーム', 'シネマ', 'ヒーリング'],
  },

  // ↓ 新しい曲はここに追加 ↓
];
